package cambridge.parser.tokens;

/**
 * DocTypeTokens are generated by the Tokenizer when it encounters valid
 * XML/HTML Doctype declarations. Doctypes start with "<!DOCTYPE " characters
 * in the beginning of the documents.
 */
public class DocTypeToken extends Token {
   public DocTypeToken(int line, int c, String val, int nl, int nc) {
      super(line, c, val, nl, nc);
   }

   public TokenType getType() {
      return TokenType.DOC_TYPE;
   }
}
